
// QQ表情插件
;(function ($) {

    $.fn.myFace = function (options) {
        var defaults = {
            expId : "face-"+ new Date().valueOf(),
            input: ".exp-inp",
            content: "body",
            clickHide : false
        };
        var settings = $.extend(defaults, options);
        return this.each(function(){
            var QQFaceMap = {
                "微笑": "0",
                "撇嘴": "1",
                "色": "2",
                "发呆": "3",
                "得意": "4",
                "流泪": "5",
                "害羞": "6",
                "闭嘴": "7",
                "睡": "8",
                "大哭": "9",
                "尴尬": "10",
                "发怒": "11",
                "调皮": "12",
                "呲牙": "13",
                "惊讶": "14",
                "难过": "15",
                "酷": "16",
                "冷汗": "17",
                "抓狂": "18",
                "吐": "19",
                "偷笑": "20",
                "可爱": "21",
                "愉快": "21",
                "白眼": "22",
                "傲慢": "23",
                "饥饿": "24",
                "困": "25",
                "惊恐": "26",
                "流汗": "27",
                "憨笑": "28",
                "悠闲": "29",
                "大兵": "29",
                "奋斗": "30",
                "咒骂": "31",
                "疑问": "32",
                "嘘": "33",
                "晕": "34",
                "疯了": "35",
                "折磨": "35",
                "衰": "36",
                "骷髅": "37",
                "敲打": "38",
                "再见": "39",
                "擦汗": "40",
                "抠鼻": "41",
                "鼓掌": "42",
                "糗大了": "43",
                "坏笑": "44",
                "左哼哼": "45",
                "右哼哼": "46",
                "哈欠": "47",
                "鄙视": "48",
                "委屈": "49",
                "快哭了": "50",
                "阴险": "51",
                "亲亲": "52",
                "吓": "53",
                "可怜": "54",
                "菜刀": "55",
                "西瓜": "56",
                "啤酒": "57",
                "篮球": "58",
                "乒乓": "59",
                "咖啡": "60",
                "饭": "61",
                "猪头": "62",
                "玫瑰": "63",
                "凋谢": "64",
                "嘴唇": "65",
                "示爱": "65",
                "爱心": "66",
                "心碎": "67",
                "蛋糕": "68",
                "闪电": "69",
                "炸弹": "70",
                "刀": "71",
                "足球": "72",
                "瓢虫": "73",
                "便便": "74",
                "月亮": "75",
                "太阳": "76",
                "礼物": "77",
                "拥抱": "78",
                "强": "79",
                "弱": "80",
                "握手": "81",
                "胜利": "82",
                "抱拳": "83",
                "勾引": "84",
                "拳头": "85",
                "差劲": "86",
                "爱你": "87",
                NO: "88",
                OK: "89",
                "爱情": "90",
                "飞吻": "91",
                "跳跳": "92",
                "发抖": "93",
                "怄火": "94",
                "转圈": "95",
                "磕头": "96",
                "回头": "97",
                "跳绳": "98",
                "投降": "99",
                "激动": "100",
                "乱舞": "101",
                "献吻": "102",
                "左太极": "103",
                "右太极": "104",
                "嘿哈": "105",
                "捂脸": "106",
                "奸笑": "107",
                "机智": "108",
                "皱眉": "109",
                "耶": "110",
                "鸡": "111",
                "红包": "112",
                Smile: "0",
                Grimace: "1",
                Drool: "2",
                Scowl: "3",
                Chill: "4",
                CoolGuy: "4",
                Sob: "5",
                Shy: "6",
                Shutup: "7",
                Silent: "7",
                Sleep: "8",
                Cry: "9",
                Awkward: "10",
                Pout: "11",
                Angry: "11",
                Wink: "12",
                Tongue: "12",
                Grin: "13",
                Surprised: "14",
                Surprise: "14",
                Frown: "15",
                Cool: "16",
                Ruthless: "16",
                Tension: "17",
                Blush: "17",
                Scream: "18",
                Crazy: "18",
                Puke: "19",
                Chuckle: "20",
                Joyful: "21",
                Slight: "22",
                Smug: "23",
                Hungry: "24",
                Drowsy: "25",
                Panic: "26",
                Sweat: "27",
                Laugh: "28",
                Loafer: "29",
                Commando: "29",
                Strive: "30",
                Determined: "30",
                Scold: "31",
                Doubt: "32",
                Shocked: "32",
                Shhh: "33",
                Dizzy: "34",
                Tormented: "35",
                BadLuck: "36",
                Toasted: "36",
                Skull: "37",
                Hammer: "38",
                Wave: "39",
                Relief: "40",
                Speechless: "40",
                DigNose: "41",
                NosePick: "41",
                Clap: "42",
                Shame: "43",
                Trick: "44",
                "Bah！L": "45",
                "Bah！R": "46",
                Yawn: "47",
                Lookdown: "48",
                "Pooh-pooh": "48",
                Wronged: "49",
                Shrunken: "49",
                Puling: "50",
                TearingUp: "50",
                Sly: "51",
                Kiss: "52",
                "Uh-oh": "53",
                Wrath: "53",
                Whimper: "54",
                Cleaver: "55",
                Melon: "56",
                Watermelon: "56",
                Beer: "57",
                Basketball: "58",
                PingPong: "59",
                Coffee: "60",
                Rice: "61",
                Pig: "62",
                Rose: "63",
                Wilt: "64",
                Lip: "65",
                Lips: "65",
                Heart: "66",
                BrokenHeart: "67",
                Cake: "68",
                Lightning: "69",
                Bomb: "70",
                Dagger: "71",
                Soccer: "72",
                Ladybug: "73",
                Poop: "74",
                Moon: "75",
                Sun: "76",
                Gift: "77",
                Hug: "78",
                Strong: "79",
                ThumbsUp: "79",
                Weak: "80",
                ThumbsDown: "80",
                Shake: "81",
                Victory: "82",
                Peace: "82",
                Admire: "83",
                Fight: "83",
                Beckon: "84",
                Fist: "85",
                Pinky: "86",
                Love: "2",
                RockOn: "87",
                No: "88",
                "Nuh-uh": "88",
                InLove: "90",
                Blowkiss: "91",
                Waddle: "92",
                Tremble: "93",
                "Aaagh!": "94",
                Twirl: "95",
                Kotow: "96",
                Lookback: "97",
                Dramatic: "97",
                Jump: "98",
                JumpRope: "98",
                "Give-in": "99",
                Surrender: "99",
                Hooray: "100",
                HeyHey: "101",
                Meditate: "101",
                Smooch: "102",
                "TaiJi L": "103",
                "TaiChi L": "103",
                "TaiJi R": "104",
                "TaiChi R": "104",
                Hey: "105",
                Facepalm: "106",
                Smirk: "107",
                Smart: "108",
                Concerned: "109",
                "Yeah!": "110",
                Chicken: "111",
                Packet: "112",
                "發呆": "3",
                "流淚": "5",
                "閉嘴": "7",
                "尷尬": "10",
                "發怒": "11",
                "調皮": "12",
                "驚訝": "14",
                "難過": "15",
                "饑餓": "24",
                "累": "25",
                "驚恐": "26",
                "悠閑": "29",
                "奮鬥": "30",
                "咒罵": "31",
                "疑問": "32",
                "噓": "33",
                "暈": "34",
                "瘋了": "35",
                "骷髏頭": "37",
                "再見": "39",
                "摳鼻": "41",
                "羞辱": "43",
                "壞笑": "44",
                "鄙視": "48",
                "陰險": "51",
                "親親": "52",
                "嚇": "53",
                "可憐": "54",
                "籃球": "58",
                "飯": "61",
                "豬頭": "62",
                "枯萎": "64",
                "愛心": "66",
                "閃電": "69",
                "炸彈": "70",
                "甲蟲": "73",
                "太陽": "76",
                "禮物": "77",
                "擁抱": "78",
                "強": "79",
                "勝利": "82",
                "拳頭": "85",
                "差勁": "86",
                "愛你": "88",
                "愛情": "90",
                "飛吻": "91",
                "發抖": "93",
                "噴火": "94",
                "轉圈": "95",
                "磕頭": "96",
                "回頭": "97",
                "跳繩": "98",
                "激動": "100",
                "亂舞": "101",
                "獻吻": "102",
                "左太極": "103",
                "右太極": "104",
                "吼嘿": "105",
                "掩面": "106",
                "機智": "108",
                "皺眉": "109",
                "歐耶": "110",
                "雞": "111",
                "紅包": "112",
                "<笑脸>": "1f604",
                "<笑臉>": "1f604",
                "<Laugh>": "1f604",
                "<开心>": "1f60a",
                "<開心>": "1f60a",
                "<Happy>": "1f60a",
                "<大笑>": "1f603",
                "<Big Smile>": "1f603",
                "<热情>": "263a",
                "<熱情>": "263a",
                "<Glowing>": "263a",
                "<眨眼>": "1f609",
                "<Wink>": "1f609",
                "<色>": "1f60d",
                "<Love>": "1f60d",
                "<Drool>": "1f60d",
                "<接吻>": "1f618",
                "<Smooch>": "1f618",
                "<亲吻>": "1f61a",
                "<親吻>": "1f61a",
                "<Kiss>": "1f61a",
                "<脸红>": "1f633",
                "<臉紅>": "1f633",
                "<Blush>": "1f633",
                "<露齿笑>": "1f63c",
                "<露齒笑>": "1f63c",
                "<Grin>": "1f63c",
                "<满意>": "1f60c",
                "<滿意>": "1f60c",
                "<Satisfied>": "1f60c",
                "<戏弄>": "1f61c",
                "<戲弄>": "1f61c",
                "<Tease>": "1f61c",
                "<吐舌>": "1f445",
                "<Tongue>": "1f445",
                "<无语>": "1f612",
                "<無語>": "1f612",
                "<Speechless>": "1f612",
                "<得意>": "1f60f",
                "<Smirk>": "1f60f",
                "<CoolGuy>": "1f60f",
                "<汗>": "1f613",
                "<Sweat>": "1f613",
                "<失望>": "1f640",
                "<Let Down>": "1f640",
                "<合十>": "1f64f",
                "<祈禱>": "1f64f",
                "<低落>": "1f61e",
                "<Low>": "1f61e",
                "<呸>": "1f616",
                "<Ugh>": "1f616",
                "<焦虑>": "1f625",
                "<焦慮>": "1f625",
                "<Anxious>": "1f625",
                "<担心>": "1f630",
                "<擔心>": "1f630",
                "<Worried>": "1f630",
                "<震惊>": "1f628",
                "<震驚>": "1f628",
                "<Shocked>": "1f628",
                "<悔恨>": "1f62b",
                "<D’oh!>": "1f62b",
                "<眼泪>": "1f622",
                "<眼淚>": "1f622",
                "<Tear>": "1f622",
                "<哭>": "1f62d",
                "<Cry>": "1f62d",
                "<破涕为笑>": "1f602",
                "<破涕為笑>": "1f602",
                "<Lol>": "1f602",
                "<晕>": "1f632",
                "<Dead>": "1f632",
                "<Dizzy>": "1f632",
                "<恐惧>": "1f631",
                "<恐懼>": "1f631",
                "<Terror>": "1f631",
                "<心烦>": "1f620",
                "<心煩>": "1f620",
                "<Upset>": "1f620",
                "<生气>": "1f63e",
                "<生氣>": "1f63e",
                "<Angry>": "1f63e",
                "<睡觉>": "1f62a",
                "<睡覺>": "1f62a",
                "<Zzz>": "1f62a",
                "<生病>": "1f637",
                "<Sick>": "1f637",
                "<恶魔>": "1f47f",
                "<惡魔>": "1f47f",
                "<Demon>": "1f47f",
                "<外星人>": "1f47d",
                "<Alien>": "1f47d",
                "<心>": "2764",
                "<Heart>": "2764",
                "<心碎>": "1f494",
                "<Heartbroken>": "1f494",
                "<BrokenHeart>": "1f494",
                "<丘比特>": "1f498",
                "<Cupid>": "1f498",
                "<闪烁>": "2728",
                "<閃爍>": "2728",
                "<Twinkle>": "2728",
                "<星星>": "1f31f",
                "<Star>": "1f31f",
                "<叹号>": "2755",
                "<嘆號>": "2755",
                "<!>": "2755",
                "<问号>": "2754",
                "<問號>": "2754",
                "<?>": "2754",
                "<睡着>": "1f4a4",
                "<睡著>": "1f4a4",
                "<Asleep>": "1f4a4",
                "<水滴>": "1f4a6",
                "<Drops>": "1f4a6",
                "<音乐>": "1f3b5",
                "<音樂>": "1f3b5",
                "<Music>": "1f3b5",
                "<火>": "1f525",
                "<Fire>": "1f525",
                "<便便>": "1f4a9",
                "<Poop>": "1f4a9",
                "<强>": "1f44d",
                "<強>": "1f44d",
                "<ThumbsUp>": "1f44d",
                "<弱>": "1f44e",
                "<ThumbsDown>": "1f44e",
                "<拳头>": "1f44a",
                "<拳頭>": "1f44a",
                "<Punch>": "1f44a",
                "<Fist>": "1f44a",
                "<胜利>": "270c",
                "<勝利>": "270c",
                "<Peace>": "270c",
                "<上>": "1f446",
                "<Up>": "1f446",
                "<下>": "1f447",
                "<Down>": "1f447",
                "<右>": "1f449",
                "<Right>": "1f449",
                "<左>": "1f448",
                "<Left>": "1f448",
                "<第一>": "261d",
                "<#1>": "261d",
                "<强壮>": "1f4aa",
                "<強壯>": "1f4aa",
                "<Strong>": "1f4aa",
                "<吻>": "1f48f",
                "<Kissing>": "1f48f",
                "<热恋>": "1f491",
                "<熱戀>": "1f491",
                "<Couple>": "1f491",
                "<男孩>": "1f466",
                "<Boy>": "1f466",
                "<女孩>": "1f467",
                "<Girl>": "1f467",
                "<女士>": "1f469",
                "<Lady>": "1f469",
                "<男士>": "1f468",
                "<Man>": "1f468",
                "<天使>": "1f47c",
                "<Angel>": "1f47c",
                "<骷髅>": "1f480",
                "<骷髏頭>": "1f480",
                "<骷髏>": "1f480",
                "<Skull>": "1f480",
                "<红唇>": "1f48b",
                "<紅唇>": "1f48b",
                "<Lips>": "1f48b",
                "<太阳>": "2600",
                "<太陽>": "2600",
                "<Sun>": "2600",
                "<下雨>": "2614",
                "<Rain>": "2614",
                "<多云>": "2601",
                "<多雲>": "2601",
                "<Cloud>": "2601",
                "<雪人>": "26c4",
                "<Snowman>": "26c4",
                "<月亮>": "1f319",
                "<Moon>": "1f319",
                "<闪电>": "26a1",
                "<閃電>": "26a1",
                "<Lightning>": "26a1",
                "<海浪>": "1f30a",
                "<Waves>": "1f30a",
                "<猫>": "1f431",
                "<貓>": "1f431",
                "<Cat>": "1f431",
                "<小狗>": "1f429",
                "<Doggy>": "1f429",
                "<老鼠>": "1f42d",
                "<Mouse>": "1f42d",
                "<仓鼠>": "1f439",
                "<倉鼠>": "1f439",
                "<Hamster>": "1f439",
                "<兔子>": "1f430",
                "<Rabbit>": "1f430",
                "<狗>": "1f43a",
                "<Dog>": "1f43a",
                "<青蛙>": "1f438",
                "<Frog>": "1f438",
                "<老虎>": "1f42f",
                "<Tiger>": "1f42f",
                "<考拉>": "1f428",
                "<Koala>": "1f428",
                "<熊>": "1f43b",
                "<Bear>": "1f43b",
                "<猪>": "1f437",
                "<豬>": "1f437",
                "<Pig>": "1f437",
                "<牛>": "1f42e",
                "<Cow>": "1f42e",
                "<野猪>": "1f417",
                "<野豬>": "1f417",
                "<Boar>": "1f417",
                "<猴子>": "1f435",
                "<Monkey>": "1f435",
                "<马>": "1f434",
                "<馬>": "1f434",
                "<Horse>": "1f434",
                "<蛇>": "1f40d",
                "<Snake>": "1f40d",
                "<鸽子>": "1f426",
                "<鴿子>": "1f426",
                "<Pigeon>": "1f426",
                "<鸡>": "1f414",
                "<雞>": "1f414",
                "<Chicken>": "1f414",
                "<企鹅>": "1f427",
                "<企鵝>": "1f427",
                "<Penguin>": "1f427",
                "<毛虫>": "1f41b",
                "<毛蟲>": "1f41b",
                "<Caterpillar>": "1f41b",
                "<章鱼>": "1f419",
                "<八爪魚>": "1f419",
                "<Octopus>": "1f419",
                "<鱼>": "1f420",
                "<魚>": "1f420",
                "<Fish>": "1f420",
                "<鲸鱼>": "1f433",
                "<鯨魚>": "1f433",
                "<Whale>": "1f433",
                "<海豚>": "1f42c",
                "<Dolphin>": "1f42c",
                "<玫瑰>": "1f339",
                "<Rose>": "1f339",
                "<花>": "1f33a",
                "<Flower>": "1f33a",
                "<棕榈树>": "1f334",
                "<棕櫚樹>": "1f334",
                "<Palm>": "1f334",
                "<仙人掌>": "1f335",
                "<Cactus>": "1f335",
                "<礼盒>": "1f49d",
                "<禮盒>": "1f49d",
                "<Candy Box>": "1f49d",
                "<南瓜灯>": "1f383",
                "<南瓜燈>": "1f383",
                "<Jack-o-lantern>": "1f383",
                "<鬼魂>": "1f47b",
                "<Ghost>": "1f47b",
                "<圣诞老人>": "1f385",
                "<聖誕老人>": "1f385",
                "<Santa>": "1f385",
                "<圣诞树>": "1f384",
                "<聖誕樹>": "1f384",
                "<Xmas Tree>": "1f384",
                "<礼物>": "1f381",
                "<禮物>": "1f381",
                "<Gift>": "1f381",
                "<铃>": "1f514",
                "<鈴鐺>": "1f514",
                "<Bell>": "1f514",
                "<庆祝>": "1f389",
                "<慶祝>": "1f389",
                "<Party>": "1f389",
                "<气球>": "1f388",
                "<氣球>": "1f388",
                "<Balloon>": "1f388",
                "<CD>": "1f4bf",
                "<相机>": "1f4f7",
                "<相機>": "1f4f7",
                "<Camera>": "1f4f7",
                "<录像机>": "1f3a5",
                "<錄影機>": "1f3a5",
                "<Film Camera>": "1f3a5",
                "<电脑>": "1f4bb",
                "<電腦>": "1f4bb",
                "<Computer>": "1f4bb",
                "<电视>": "1f4fa",
                "<電視>": "1f4fa",
                "<TV>": "1f4fa",
                "<电话>": "1f4de",
                "<電話>": "1f4de",
                "<Phone>": "1f4de",
                "<解锁>": "1f513",
                "<解鎖>": "1f513",
                "<Unlocked>": "1f513",
                "<锁>": "1f512",
                "<鎖>": "1f512",
                "<Locked>": "1f512",
                "<钥匙>": "1f511",
                "<鑰匙>": "1f511",
                "<Key>": "1f511",
                "<成交>": "1f528",
                "<Judgement>": "1f528",
                "<灯泡>": "1f4a1",
                "<燈泡>": "1f4a1",
                "<Light bulb>": "1f4a1",
                "<邮箱>": "1f4eb",
                "<郵箱>": "1f4eb",
                "<Mail>": "1f4eb",
                "<浴缸>": "1f6c0",
                "<Wash>": "1f6c0",
                "<钱>": "1f4b2",
                "<錢>": "1f4b2",
                "<Money>": "1f4b2",
                "<炸弹>": "1f4a3",
                "<炸彈>": "1f4a3",
                "<Bomb>": "1f4a3",
                "<手枪>": "1f52b",
                "<手槍>": "1f52b",
                "<Pistol>": "1f52b",
                "<药丸>": "1f48a",
                "<藥丸>": "1f48a",
                "<Pill>": "1f48a",
                "<橄榄球>": "1f3c8",
                "<橄欖球>": "1f3c8",
                "<Football>": "1f3c8",
                "<篮球>": "1f3c0",
                "<籃球>": "1f3c0",
                "<Basketball>": "1f3c0",
                "<足球>": "26bd",
                "<Soccer Ball>": "26bd",
                "<Soccer>": "26bd",
                "<棒球>": "26be",
                "<Baseball>": "26be",
                "<高尔夫>": "26f3",
                "<高爾夫>": "26f3",
                "<Golf>": "26f3",
                "<奖杯>": "1f3c6",
                "<獎盃>": "1f3c6",
                "<Trophy>": "1f3c6",
                "<入侵者>": "1f47e",
                "<Invader>": "1f47e",
                "<唱歌>": "1f3a4",
                "<Singing>": "1f3a4",
                "<吉他>": "1f3b8",
                "<Guitar>": "1f3b8",
                "<比基尼>": "1f459",
                "<Bikini>": "1f459",
                "<皇冠>": "1f451",
                "<Crown>": "1f451",
                "<雨伞>": "1f302",
                "<雨傘>": "1f302",
                "<Umbrella>": "1f302",
                "<手提包>": "1f45c",
                "<Purse>": "1f45c",
                "<口红>": "1f484",
                "<口紅>": "1f484",
                "<Lipstick>": "1f484",
                "<戒指>": "1f48d",
                "<Ring>": "1f48d",
                "<钻石>": "1f48e",
                "<鑽石>": "1f48e",
                "<Gem>": "1f48e",
                "<咖啡>": "2615",
                "<Coffee>": "2615",
                "<啤酒>": "1f37a",
                "<Beer>": "1f37a",
                "<干杯>": "1f37b",
                "<乾杯>": "1f37b",
                "<Toast>": "1f37b",
                "<鸡尾酒>": "1f377",
                "<雞尾酒>": "1f377",
                "<Martini>": "1f377",
                "<汉堡>": "1f354",
                "<漢堡>": "1f354",
                "<Burger>": "1f354",
                "<薯条>": "1f35f",
                "<薯條>": "1f35f",
                "<Fries>": "1f35f",
                "<意面>": "1f35d",
                "<意粉>": "1f35d",
                "<Sphaghetti>": "1f35d",
                "<寿司>": "1f363",
                "<壽司>": "1f363",
                "<Sushi>": "1f363",
                "<面条>": "1f35c",
                "<麵條>": "1f35c",
                "<Noodles>": "1f35c",
                "<煎蛋>": "1f373",
                "<Eggs>": "1f373",
                "<冰激凌>": "1f366",
                "<雪糕>": "1f366",
                "<Ice Cream>": "1f366",
                "<蛋糕>": "1f382",
                "<Cake>": "1f382",
                "<苹果>": "1f34f",
                "<蘋果>": "1f34f",
                "<Apple>": "1f34f",
                "<飞机>": "2708",
                "<飛機>": "2708",
                "<Plane>": "2708",
                "<火箭>": "1f680",
                "<Rocket ship>": "1f680",
                "<自行车>": "1f6b2",
                "<單車>": "1f6b2",
                "<Bike>": "1f6b2",
                "<高铁>": "1f684",
                "<高鐵>": "1f684",
                "<Bullet Train>": "1f684",
                "<警告>": "26a0",
                "<Warning>": "26a0",
                "<旗>": "1f3c1",
                "<Flag>": "1f3c1",
                "<男人>": "1f6b9",
                "<男>": "1f6b9",
                "<Men>": "1f6b9",
                "<女人>": "1f6ba",
                "<女>": "1f6ba",
                "<Women>": "1f6ba",
                "<O>": "2b55",
                "<X>": "274e",
                "<版权>": "a9",
                "<版權>": "a9",
                "<Copyright>": "a9",
                "<注册商标>": "ae",
                "<注冊商標>": "ae",
                "<Registered TM>": "ae",
                "<商标>": "2122",
                "<商標>": "2122",
                "<Trademark>": "2122"
            };
            var emojiWeixinObj = {
                "葡萄": "🍇",
                "甜瓜": "🍈",
                "西瓜": "🍉",
                "橘子": "🍊",
                "柠檬": "🍋",
                "香蕉": "🍌",
                "菠萝": "🍍",
                "红苹果": "🍎",
                "青苹果": "🍏",
                "梨": "🍐",
                "桃": "🍑",
                "樱桃": "🍒",
                "草莓": "🍓",
                "猕猴桃": "🥝",
                "番茄": "🍅",
                "牛油果": "🥑",
                "茄子": "🍆",
                "土豆": "🥔",
                "胡萝卜": "🥕",
                "玉米": "🌽",
                "辣椒": "🌶",
                "黄瓜": "🥒",
                "蘑菇": "🍄",
                "花生": "🥜",
                "栗子": "🌰",
                "面包": "🍞",
                "羊角面包": "🥐",
                "烙饼": "🥞",
                "奶酪楔形": "🧀",
                "肉类": "🍖",
                "禽肉": "🍗",
                "熏肉": "🥓",
                "汉堡包": "🍔",
                "炸薯条": "🍟",
                "披萨": "🍕",
                "热狗": "🌭",
                "墨西哥玉米卷": "🌮",
                "卷饼": "🌯",
                "夹心面包": "🥙",
                "鸡蛋": "🥚",
                "烹饪": "🍳",
                "浅盘食物": "🥘",
                "一锅食物": "🍲",
                "蔬菜沙拉": "🥗",
                "爆米花": "🍿",
                "便当盒": "🍱",
                "香米饼": "🍘",
                "饭团": "🍙",
                "熟米饭": "🍚",
                "咖喱饭": "🍛",
                "蒸碗": "🍜",
                "意大利面": "🍝",
                "烤红薯": "🍠",
                "关东煮": "🍢",
                "寿司": "🍣",
                "炸虾": "🍤",
                "漩涡鱼糕": "🍥",
                "鱼丸": "🍡",
                "冰淇淋": "🍦",
                "刨冰": "🍧",
                "奶油": "🍨",
                "甜甜圈": "🍩",
                "曲奇饼": "🍪",
                "生日蛋糕": "🎂",
                "水果蛋糕": "🍰",
                "巧克力条": "🍫",
                "糖果": "🍬",
                "棒棒糖": "🍭",
                "布丁": "🍮",
                "蜜罐": "🍯",
                "婴儿奶瓶": "🍼",
                "牛奶": "🥛",
                "热饮料": "☕",
                "绿茶": "🍵",
                "清酒": "🍶",
                "香槟": "🍾",
                "红酒": "🍷",
                "鸡尾酒": "🍸",
                "热带饮料": "🍹",
                "啤酒杯": "🍺",
                "干杯": "🍻",
                "碰杯": "🥂",
                "平底杯": "🥃",
                "叉刀盘": "🍽",
                "叉刀": "🍴",
                "勺子": "🥄"
            }
            var strEmojiWeixin = '';
            for (var item in emojiWeixinObj) {
                if (emojiWeixinObj.hasOwnProperty(item)) {
                    var strItem = '<a href="javascript:;" title="' + item + '" type="emoji_weixin" class="face">' + emojiWeixinObj[item] + '</a>';
                    strEmojiWeixin += strItem;
                }
            }
            //console.log(strEmojiWeixin);
            var html = '' +
                '    <div class="expression" style="display: none;" id="'+ settings.expId +'">' +
                '        <div class="exp_bd scrollbar-dynamic">' +
                '            <div class="exp_cont active">' +
                '                <div class="qq_face">' +
                '                    <a href="javascript:;" title="微笑" type="qq" class="face qqface0">微笑</a> <a href="javascript:;" title="撇嘴" type="qq" class="face qqface1">撇嘴</a> <a href="javascript:;" title="色" type="qq" class="face qqface2">色</a> <a href="javascript:;" title="发呆" type="qq" class="face qqface3">发呆</a> <a href="javascript:;" title="得意" type="qq" class="face qqface4">得意</a> <a href="javascript:;" title="流泪" type="qq" class="face qqface5">流泪</a> <a href="javascript:;" title="害羞" type="qq" class="face qqface6">害羞</a> <a href="javascript:;" title="闭嘴" type="qq" class="face qqface7">闭嘴</a> <a href="javascript:;" title="睡" type="qq" class="face qqface8">睡</a> <a href="javascript:;" title="大哭" type="qq" class="face qqface9">大哭</a> <a href="javascript:;" title="尴尬" type="qq" class="face qqface10">尴尬</a> <a href="javascript:;" title="发怒" type="qq" class="face qqface11">发怒</a> <a href="javascript:;" title="调皮" type="qq" class="face qqface12">调皮</a> <a href="javascript:;" title="呲牙" type="qq" class="face qqface13">呲牙</a> <a href="javascript:;" title="惊讶" type="qq" class="face qqface14">惊讶</a> <a href="javascript:;" title="难过" type="qq" class="face qqface15">难过</a> <a href="javascript:;" title="酷" type="qq" class="face qqface16">酷</a> <a href="javascript:;" title="冷汗" type="qq" class="face qqface17">冷汗</a> <a href="javascript:;" title="抓狂" type="qq" class="face qqface18">抓狂</a> <a href="javascript:;" title="吐" type="qq" class="face qqface19">吐</a> <a href="javascript:;" title="偷笑" type="qq" class="face qqface20">偷笑</a> <a href="javascript:;" title="愉快" type="qq" class="face qqface21">愉快</a> <a href="javascript:;" title="白眼" type="qq" class="face qqface22">白眼</a> <a href="javascript:;" title="傲慢" type="qq" class="face qqface23">傲慢</a> <a href="javascript:;" title="饥饿" type="qq" class="face qqface24">饥饿</a> <a href="javascript:;" title="困" type="qq" class="face qqface25">困</a> <a href="javascript:;" title="惊恐" type="qq" class="face qqface26">惊恐</a> <a href="javascript:;" title="流汗" type="qq" class="face qqface27">流汗</a> <a href="javascript:;" title="憨笑" type="qq" class="face qqface28">憨笑</a> <a href="javascript:;" title="悠闲" type="qq" class="face qqface29">悠闲</a> <a href="javascript:;" title="奋斗" type="qq" class="face qqface30">奋斗</a> <a href="javascript:;" title="咒骂" type="qq" class="face qqface31">咒骂</a> <a href="javascript:;" title="疑问" type="qq" class="face qqface32">疑问</a> <a href="javascript:;" title="嘘" type="qq" class="face qqface33">嘘</a> <a href="javascript:;" title="晕" type="qq" class="face qqface34">晕</a> <a href="javascript:;" title="疯了" type="qq" class="face qqface35">疯了</a> <a href="javascript:;" title="衰" type="qq" class="face qqface36">衰</a> <a href="javascript:;" title="骷髅" type="qq" class="face qqface37">骷髅</a> <a href="javascript:;" title="敲打" type="qq" class="face qqface38">敲打</a> <a href="javascript:;" title="再见" type="qq" class="face qqface39">再见</a> <a href="javascript:;" title="擦汗" type="qq" class="face qqface40">擦汗</a> <a href="javascript:;" title="抠鼻" type="qq" class="face qqface41">抠鼻</a> <a href="javascript:;" title="鼓掌" type="qq" class="face qqface42">鼓掌</a> <a href="javascript:;" title="糗大了" type="qq" class="face qqface43">糗大了</a> <a href="javascript:;" title="坏笑" type="qq" class="face qqface44">坏笑</a> <a href="javascript:;" title="左哼哼" type="qq" class="face qqface45">左哼哼</a> <a href="javascript:;" title="右哼哼" type="qq" class="face qqface46">右哼哼</a> <a href="javascript:;" title="哈欠" type="qq" class="face qqface47">哈欠</a> <a href="javascript:;" title="鄙视" type="qq" class="face qqface48">鄙视</a> <a href="javascript:;" title="委屈" type="qq" class="face qqface49">委屈</a> <a href="javascript:;" title="快哭了" type="qq" class="face qqface50">快哭了</a> <a href="javascript:;" title="阴险" type="qq" class="face qqface51">阴险</a> <a href="javascript:;" title="亲亲" type="qq" class="face qqface52">亲亲</a> <a href="javascript:;" title="吓" type="qq" class="face qqface53">吓</a> <a href="javascript:;" title="可怜" type="qq" class="face qqface54">可怜</a> <a href="javascript:;" title="菜刀" type="qq" class="face qqface55">菜刀</a> <a href="javascript:;" title="西瓜" type="qq" class="face qqface56">西瓜</a> <a href="javascript:;" title="啤酒" type="qq" class="face qqface57">啤酒</a> <a href="javascript:;" title="篮球" type="qq" class="face qqface58">篮球</a> <a href="javascript:;" title="乒乓" type="qq" class="face qqface59">乒乓</a> <a href="javascript:;" title="咖啡" type="qq" class="face qqface60">咖啡</a> <a href="javascript:;" title="饭" type="qq" class="face qqface61">饭</a> <a href="javascript:;" title="猪头" type="qq" class="face qqface62">猪头</a> <a href="javascript:;" title="玫瑰" type="qq" class="face qqface63">玫瑰</a> <a href="javascript:;" title="凋谢" type="qq" class="face qqface64">凋谢</a> <a href="javascript:;" title="嘴唇" type="qq" class="face qqface65">嘴唇</a> <a href="javascript:;" title="爱心" type="qq" class="face qqface66">爱心</a> <a href="javascript:;" title="心碎" type="qq" class="face qqface67">心碎</a> <a href="javascript:;" title="蛋糕" type="qq" class="face qqface68">蛋糕</a> <a href="javascript:;" title="闪电" type="qq" class="face qqface69">闪电</a> <a href="javascript:;" title="炸弹" type="qq" class="face qqface70">炸弹</a> <a href="javascript:;" title="刀" type="qq" class="face qqface71">刀</a> <a href="javascript:;" title="足球" type="qq" class="face qqface72">足球</a> <a href="javascript:;" title="瓢虫" type="qq" class="face qqface73">瓢虫</a> <a href="javascript:;" title="便便" type="qq" class="face qqface74">便便</a> <a href="javascript:;" title="月亮" type="qq" class="face qqface75">月亮</a> <a href="javascript:;" title="太阳" type="qq" class="face qqface76">太阳</a> <a href="javascript:;" title="礼物" type="qq" class="face qqface77">礼物</a> <a href="javascript:;" title="拥抱" type="qq" class="face qqface78">拥抱</a> <a href="javascript:;" title="强" type="qq" class="face qqface79">强</a> <a href="javascript:;" title="弱" type="qq" class="face qqface80">弱</a> <a href="javascript:;" title="握手" type="qq" class="face qqface81">握手</a> <a href="javascript:;" title="胜利" type="qq" class="face qqface82">胜利</a> <a href="javascript:;" title="抱拳" type="qq" class="face qqface83">抱拳</a> <a href="javascript:;" title="勾引" type="qq" class="face qqface84">勾引</a> <a href="javascript:;" title="拳头" type="qq" class="face qqface85">拳头</a> <a href="javascript:;" title="差劲" type="qq" class="face qqface86">差劲</a> <a href="javascript:;" title="爱你" type="qq" class="face qqface87">爱你</a> <a href="javascript:;" title="NO" type="qq" class="face qqface88">NO</a> <a href="javascript:;" title="OK" type="qq" class="face qqface89">OK</a> <a href="javascript:;" title="爱情" type="qq" class="face qqface90">爱情</a> <a href="javascript:;" title="飞吻" type="qq" class="face qqface91">飞吻</a> <a href="javascript:;" title="跳跳" type="qq" class="face qqface92">跳跳</a> <a href="javascript:;" title="发抖" type="qq" class="face qqface93">发抖</a> <a href="javascript:;" title="怄火" type="qq" class="face qqface94">怄火</a> <a href="javascript:;" title="转圈" type="qq" class="face qqface95">转圈</a> <a href="javascript:;" title="磕头" type="qq" class="face qqface96">磕头</a> <a href="javascript:;" title="回头" type="qq" class="face qqface97">回头</a> <a href="javascript:;" title="跳绳" type="qq" class="face qqface98">跳绳</a> <a href="javascript:;" title="投降" type="qq" class="face qqface99">投降</a> <a href="javascript:;" title="激动" type="qq" class="face qqface100">激动</a> <a href="javascript:;" title="乱舞" type="qq" class="face qqface101">乱舞</a> <a href="javascript:;" title="献吻" type="qq" class="face qqface102">献吻</a> <a href="javascript:;" title="左太极" type="qq" class="face qqface103">左太极</a> <a href="javascript:;" title="右太极" type="qq" class="face qqface104">右太极</a>' +
                '                </div>' +
                '                <div class="emoji_face">' +
                '                    <a href="javascript:;" title="笑脸" type="emoji" class="face emoji0">笑脸</a><a href="javascript:;" title="生病" type="emoji" class="face emoji1">生病</a><a href="javascript:;" title="破涕为笑" type="emoji" class="face emoji2">破涕为笑</a><a href="javascript:;" title="吐舌" type="emoji" class="face emoji3">吐舌</a><a href="javascript:;" title="脸红" type="emoji" class="face emoji4">脸红</a><a href="javascript:;" title="恐惧" type="emoji" class="face emoji5">恐惧</a><a href="javascript:;" title="失望" type="emoji" class="face emoji6">失望</a><a href="javascript:;" title="无语" type="emoji" class="face emoji7">无语</a><a href="javascript:;" title="嘿哈" type="qq" class="face emoji8">嘿哈</a><a href="javascript:;" title="捂脸" type="qq" class="face emoji9">捂脸</a><a href="javascript:;" title="奸笑" type="qq" class="face emoji10">奸笑</a><a href="javascript:;" title="机智" type="qq" class="face emoji11">机智</a><a href="javascript:;" title="皱眉" type="qq" class="face emoji12">皱眉</a><a href="javascript:;" title="耶" type="qq" class="face emoji13">耶</a><a href="javascript:;" title="鬼魂" type="emoji" class="face emoji14">鬼魂</a><a href="javascript:;" title="合十" type="emoji" class="face emoji15">合十</a><a href="javascript:;" title="强壮" type="emoji" class="face emoji16">强壮</a><a href="javascript:;" title="庆祝" type="emoji" class="face emoji17">庆祝</a><a href="javascript:;" title="礼物" type="emoji" class="face emoji18">礼物</a><a href="javascript:;" title="红包" type="qq" class="face emoji19">红包</a><a href="javascript:;" title="鸡" type="qq" class="face emoji20">鸡</a><a href="javascript:;" title="开心" type="emoji" class="face emoji21">开心</a><a href="javascript:;" title="大笑" type="emoji" class="face emoji22">大笑</a><a href="javascript:;" title="热情" type="emoji" class="face emoji23">热情</a><a href="javascript:;" title="眨眼" type="emoji" class="face emoji24">眨眼</a><a href="javascript:;" title="色" type="emoji" class="face emoji25">色</a><a href="javascript:;" title="接吻" type="emoji" class="face emoji26">接吻</a><a href="javascript:;" title="亲吻" type="emoji" class="face emoji27">亲吻</a><a href="javascript:;" title="露齿笑" type="emoji" class="face emoji28">露齿笑</a><a href="javascript:;" title="满意" type="emoji" class="face emoji29">满意</a><a href="javascript:;" title="戏弄" type="emoji" class="face emoji30">戏弄</a><a href="javascript:;" title="得意" type="emoji" class="face emoji31">得意</a><a href="javascript:;" title="汗" type="emoji" class="face emoji32">汗</a><a href="javascript:;" title="低落" type="emoji" class="face emoji33">低落</a><a href="javascript:;" title="呸" type="emoji" class="face emoji34">呸</a><a href="javascript:;" title="焦虑" type="emoji" class="face emoji35">焦虑</a><a href="javascript:;" title="担心" type="emoji" class="face emoji36">担心</a><a href="javascript:;" title="震惊" type="emoji" class="face emoji37">震惊</a><a href="javascript:;" title="悔恨" type="emoji" class="face emoji38">悔恨</a><a href="javascript:;" title="眼泪" type="emoji" class="face emoji39">眼泪</a><a href="javascript:;" title="哭" type="emoji" class="face emoji40">哭</a><a href="javascript:;" title="晕" type="emoji" class="face emoji41">晕</a><a href="javascript:;" title="心烦" type="emoji" class="face emoji42">心烦</a><a href="javascript:;" title="生气" type="emoji" class="face emoji43">生气</a><a href="javascript:;" title="睡觉" type="emoji" class="face emoji44">睡觉</a><a href="javascript:;" title="恶魔" type="emoji" class="face emoji45">恶魔</a><a href="javascript:;" title="外星人" type="emoji" class="face emoji46">外星人</a><a href="javascript:;" title="心" type="emoji" class="face emoji47">心</a><a href="javascript:;" title="心碎" type="emoji" class="face emoji48">心碎</a><a href="javascript:;" title="丘比特" type="emoji" class="face emoji49">丘比特</a><a href="javascript:;" title="闪烁" type="emoji" class="face emoji50">闪烁</a><a href="javascript:;" title="星星" type="emoji" class="face emoji51">星星</a><a href="javascript:;" title="叹号" type="emoji" class="face emoji52">叹号</a><a href="javascript:;" title="问号" type="emoji" class="face emoji53">问号</a><a href="javascript:;" title="睡着" type="emoji" class="face emoji54">睡着</a><a href="javascript:;" title="水滴" type="emoji" class="face emoji55">水滴</a><a href="javascript:;" title="音乐" type="emoji" class="face emoji56">音乐</a><a href="javascript:;" title="火" type="emoji" class="face emoji57">火</a><a href="javascript:;" title="便便" type="emoji" class="face emoji58">便便</a><a href="javascript:;" title="强" type="emoji" class="face emoji59">强</a><a href="javascript:;" title="弱" type="emoji" class="face emoji60">弱</a><a href="javascript:;" title="拳头" type="emoji" class="face emoji61">拳头</a><a href="javascript:;" title="胜利" type="emoji" class="face emoji62">胜利</a><a href="javascript:;" title="上" type="emoji" class="face emoji63">上</a><a href="javascript:;" title="下" type="emoji" class="face emoji64">下</a><a href="javascript:;" title="右" type="emoji" class="face emoji65">右</a><a href="javascript:;" title="左" type="emoji" class="face emoji66">左</a><a href="javascript:;" title="第一" type="emoji" class="face emoji67">第一</a><a href="javascript:;" title="吻" type="emoji" class="face emoji68">吻</a><a href="javascript:;" title="热恋" type="emoji" class="face emoji69">热恋</a><a href="javascript:;" title="男孩" type="emoji" class="face emoji70">男孩</a><a href="javascript:;" title="女孩" type="emoji" class="face emoji71">女孩</a><a href="javascript:;" title="女士" type="emoji" class="face emoji72">女士</a><a href="javascript:;" title="男士" type="emoji" class="face emoji73">男士</a><a href="javascript:;" title="天使" type="emoji" class="face emoji74">天使</a><a href="javascript:;" title="骷髅" type="emoji" class="face emoji75">骷髅</a><a href="javascript:;" title="红唇" type="emoji" class="face emoji76">红唇</a><a href="javascript:;" title="太阳" type="emoji" class="face emoji77">太阳</a><a href="javascript:;" title="下雨" type="emoji" class="face emoji78">下雨</a><a href="javascript:;" title="多云" type="emoji" class="face emoji79">多云</a><a href="javascript:;" title="雪人" type="emoji" class="face emoji80">雪人</a><a href="javascript:;" title="月亮" type="emoji" class="face emoji81">月亮</a><a href="javascript:;" title="闪电" type="emoji" class="face emoji82">闪电</a><a href="javascript:;" title="海浪" type="emoji" class="face emoji83">海浪</a><a href="javascript:;" title="猫" type="emoji" class="face emoji84">猫</a><a href="javascript:;" title="小狗" type="emoji" class="face emoji85">小狗</a><a href="javascript:;" title="老鼠" type="emoji" class="face emoji86">老鼠</a><a href="javascript:;" title="仓鼠" type="emoji" class="face emoji87">仓鼠</a><a href="javascript:;" title="兔子" type="emoji" class="face emoji88">兔子</a><a href="javascript:;" title="狗" type="emoji" class="face emoji89">狗</a><a href="javascript:;" title="青蛙" type="emoji" class="face emoji90">青蛙</a><a href="javascript:;" title="老虎" type="emoji" class="face emoji91">老虎</a><a href="javascript:;" title="考拉" type="emoji" class="face emoji92">考拉</a><a href="javascript:;" title="熊" type="emoji" class="face emoji93">熊</a><a href="javascript:;" title="猪" type="emoji" class="face emoji94">猪</a><a href="javascript:;" title="牛" type="emoji" class="face emoji95">牛</a><a href="javascript:;" title="野猪" type="emoji" class="face emoji96">野猪</a><a href="javascript:;" title="猴子" type="emoji" class="face emoji97">猴子</a><a href="javascript:;" title="马" type="emoji" class="face emoji98">马</a><a href="javascript:;" title="蛇" type="emoji" class="face emoji99">蛇</a><a href="javascript:;" title="鸽子" type="emoji" class="face emoji100">鸽子</a><a href="javascript:;" title="鸡" type="emoji" class="face emoji101">鸡</a><a href="javascript:;" title="企鹅" type="emoji" class="face emoji102">企鹅</a><a href="javascript:;" title="毛虫" type="emoji" class="face emoji103">毛虫</a><a href="javascript:;" title="章鱼" type="emoji" class="face emoji104">章鱼</a><a href="javascript:;" title="鱼" type="emoji" class="face emoji105">鱼</a><a href="javascript:;" title="鲸鱼" type="emoji" class="face emoji106">鲸鱼</a><a href="javascript:;" title="海豚" type="emoji" class="face emoji107">海豚</a><a href="javascript:;" title="玫瑰" type="emoji" class="face emoji108">玫瑰</a><a href="javascript:;" title="花" type="emoji" class="face emoji109">花</a><a href="javascript:;" title="棕榈树" type="emoji" class="face emoji110">棕榈树</a><a href="javascript:;" title="仙人掌" type="emoji" class="face emoji111">仙人掌</a><a href="javascript:;" title="礼盒" type="emoji" class="face emoji112">礼盒</a><a href="javascript:;" title="南瓜灯" type="emoji" class="face emoji113">南瓜灯</a><a href="javascript:;" title="圣诞老人" type="emoji" class="face emoji114">圣诞老人</a><a href="javascript:;" title="圣诞树" type="emoji" class="face emoji115">圣诞树</a><a href="javascript:;" title="铃" type="emoji" class="face emoji116">铃</a><a href="javascript:;" title="气球" type="emoji" class="face emoji117">气球</a><a href="javascript:;" title="CD" type="emoji" class="face emoji118">CD</a><a href="javascript:;" title="相机" type="emoji" class="face emoji119">相机</a><a href="javascript:;" title="录像机" type="emoji" class="face emoji120">录像机</a><a href="javascript:;" title="电脑" type="emoji" class="face emoji121">电脑</a><a href="javascript:;" title="电视" type="emoji" class="face emoji122">电视</a><a href="javascript:;" title="电话" type="emoji" class="face emoji123">电话</a><a href="javascript:;" title="解锁" type="emoji" class="face emoji124">解锁</a><a href="javascript:;" title="锁" type="emoji" class="face emoji125">锁</a><a href="javascript:;" title="钥匙" type="emoji" class="face emoji126">钥匙</a><a href="javascript:;" title="成交" type="emoji" class="face emoji127">成交</a><a href="javascript:;" title="灯泡" type="emoji" class="face emoji128">灯泡</a><a href="javascript:;" title="邮箱" type="emoji" class="face emoji129">邮箱</a><a href="javascript:;" title="浴缸" type="emoji" class="face emoji130">浴缸</a><a href="javascript:;" title="钱" type="emoji" class="face emoji131">钱</a><a href="javascript:;" title="炸弹" type="emoji" class="face emoji132">炸弹</a><a href="javascript:;" title="手枪" type="emoji" class="face emoji133">手枪</a><a href="javascript:;" title="药丸" type="emoji" class="face emoji134">药丸</a><a href="javascript:;" title="橄榄球" type="emoji" class="face emoji135">橄榄球</a><a href="javascript:;" title="篮球" type="emoji" class="face emoji136">篮球</a><a href="javascript:;" title="足球" type="emoji" class="face emoji137">足球</a><a href="javascript:;" title="棒球" type="emoji" class="face emoji138">棒球</a><a href="javascript:;" title="高尔夫" type="emoji" class="face emoji139">高尔夫</a><a href="javascript:;" title="奖杯" type="emoji" class="face emoji140">奖杯</a><a href="javascript:;" title="入侵者" type="emoji" class="face emoji141">入侵者</a><a href="javascript:;" title="唱歌" type="emoji" class="face emoji142">唱歌</a><a href="javascript:;" title="吉他" type="emoji" class="face emoji143">吉他</a><a href="javascript:;" title="比基尼" type="emoji" class="face emoji144">比基尼</a><a href="javascript:;" title="皇冠" type="emoji" class="face emoji145">皇冠</a><a href="javascript:;" title="雨伞" type="emoji" class="face emoji146">雨伞</a><a href="javascript:;" title="手提包" type="emoji" class="face emoji147">手提包</a><a href="javascript:;" title="口红" type="emoji" class="face emoji148">口红</a><a href="javascript:;" title="戒指" type="emoji" class="face emoji149">戒指</a><a href="javascript:;" title="钻石" type="emoji" class="face emoji150">钻石</a><a href="javascript:;" title="咖啡" type="emoji" class="face emoji151">咖啡</a><a href="javascript:;" title="啤酒" type="emoji" class="face emoji152">啤酒</a><a href="javascript:;" title="干杯" type="emoji" class="face emoji153">干杯</a><a href="javascript:;" title="鸡尾酒" type="emoji" class="face emoji154">鸡尾酒</a><a href="javascript:;" title="汉堡" type="emoji" class="face emoji155">汉堡</a><a href="javascript:;" title="薯条" type="emoji" class="face emoji156">薯条</a><a href="javascript:;" title="意面" type="emoji" class="face emoji157">意面</a><a href="javascript:;" title="寿司" type="emoji" class="face emoji158">寿司</a><a href="javascript:;" title="面条" type="emoji" class="face emoji159">面条</a><a href="javascript:;" title="煎蛋" type="emoji" class="face emoji160">煎蛋</a><a href="javascript:;" title="冰激凌" type="emoji" class="face emoji161">冰激凌</a><a href="javascript:;" title="蛋糕" type="emoji" class="face emoji162">蛋糕</a><a href="javascript:;" title="苹果" type="emoji" class="face emoji163">苹果</a><a href="javascript:;" title="飞机" type="emoji" class="face emoji164">飞机</a><a href="javascript:;" title="火箭" type="emoji" class="face emoji165">火箭</a><a href="javascript:;" title="自行车" type="emoji" class="face emoji166">自行车</a><a href="javascript:;" title="高铁" type="emoji" class="face emoji167">高铁</a><a href="javascript:;" title="警告" type="emoji" class="face emoji168">警告</a><a href="javascript:;" title="旗" type="emoji" class="face emoji169">旗</a><a href="javascript:;" title="男人" type="emoji" class="face emoji170">男人</a><a href="javascript:;" title="女人" type="emoji" class="face emoji171">女人</a><a href="javascript:;" title="O" type="emoji" class="face emoji172">O</a><a href="javascript:;" title="X" type="emoji" class="face emoji173">X</a><a href="javascript:;" title="版权" type="emoji" class="face emoji174">版权</a><a href="javascript:;" title="注册商标" type="emoji" class="face emoji175">注册商标</a><a href="javascript:;" title="商标" type="emoji" class="face emoji176">商标</a>' +
                '                </div>' +
                // '                <div class="emoji_weixin">' +
                //                     strEmojiWeixin +
                // '                </div>' +
                '            </div>' +
                '' +
                '        </div>' +
                '    </div>';

            $(settings.content).append(html);


            function insertHtmlAtCaret(html) {
                var sel, range;
                if (window.getSelection) {
                    // IE9 and non-IE
                    sel = window.getSelection();
                    if (sel.getRangeAt && sel.rangeCount) {
                        range = sel.getRangeAt(0);
                        range.deleteContents();

                        // Range.createContextualFragment() would be useful here but is
                        // only relatively recently standardized and is not supported in
                        // some browsers (IE9, for one)
                        var el = document.createElement("div");
                        el.innerHTML = html;
                        var frag = document.createDocumentFragment(), node, lastNode;
                        while ( (node = el.firstChild) ) {
                            lastNode = frag.appendChild(node);
                        }
                        range.insertNode(frag);

                        // Preserve the selection
                        if (lastNode) {
                            range = range.cloneRange();
                            range.setStartAfter(lastNode);
                            range.collapse(true);
                            sel.removeAllRanges();
                            sel.addRange(range);
                        }
                    }
                } else if (document.selection && document.selection.type != "Control") {
                    // IE < 9
                    document.selection.createRange().pasteHTML(html);
                }
            }

            $(this).click(function (e) {
                $(settings.input).focus();
                $("#"+settings.expId).toggle();
                e.stopPropagation();
            });

            $("#"+settings.expId+" .exp_hd>li").click(function(e){
                e.preventDefault();
                e.stopPropagation();
                $("#"+settings.expId+" .exp_hd>li").removeClass("active");
                $(this).addClass("active");

                $("#"+settings.expId+" .exp_bd .exp_cont").removeClass("active");
                $("#"+settings.expId+" .exp_bd .exp_cont").eq($(this).index()).addClass("active");
            });


            $("#"+settings.expId+" .exp_bd .face").click(function(e){
                var str='',
                    name = $(this).text(),
                    type = $(this).attr("type"),
                    id;

                if (type == 'qq') {
                    id = QQFaceMap[name];
                    str = '<img class="qqemoji qqemoji' + id + '" data-name="' + GetFaceSendValue(id) + '" src="/images/face-v2/spacer.gif">';
                } else if (type == 'emoji') {
                    id = QQFaceMap['<' + name + '>'];
                    str = '<img class="emoji emoji' +
                        id +
                        '" data-name="' +
                        GetFaceSendValue(id) +
                        '" src="/images/face-v2/spacer.gif">';
                } else {
                    str = name;
                }
                $(settings.input).focus();
                insertHtmlAtCaret(str);

                if(settings.clickHide){
                    $('#' + settings.expId).hide();
                }

                e.stopPropagation();
            });

            $(document).click(function(){
                $('#' + settings.expId).hide();
            });

        })
    }
})(jQuery);