//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JQB_User
    {
        public int nUserId { get; set; }
        public int nParentId { get; set; }
        public string vcAccount { get; set; }
        public string vcPwd { get; set; }
        public string vcUserName { get; set; }
        public string vcMobile { get; set; }
        public string vcHeadImage { get; set; }
        public string vcNickName { get; set; }
        public int nStatus { get; set; }
        public int nMerchId { get; set; }
        public string nCreateId { get; set; }
        public string vcAuthCode { get; set; }
        public string vcOpenId { get; set; }
        public string vcUnionId { get; set; }
        public string vcUserWxId { get; set; }
        public System.DateTime dtWxIdTime { get; set; }
        public System.DateTime dtBindTime { get; set; }
        public System.DateTime dtModifyTime { get; set; }
        public System.DateTime dtCreateTime { get; set; }
        public System.DateTime dtExpirationTime { get; set; }
        public int nUserType { get; set; }
        public System.DateTime dtLastLoginTime { get; set; }
        public string vcOperator { get; set; }
        public int nDataVersion { get; set; }
        public string vcSendCode { get; set; }
        public System.DateTime dtSendCodeTime { get; set; }
        public int nHighRiskType { get; set; }
        public int nLowRiskType { get; set; }
    }
}
